name: Scan App
on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, reopened, synchronize, closed] 
  push:
      branches:
        - main
        - feature/*
  workflow_call:

jobs:
  Inicio:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio
        run: |
          echo "este es el inicio"
  Logica:
    needs: "Inicio"
    runs-on: ubuntu-latest
    steps:
      - name: Logica
        run: |
         echo "este es el job de logica"
  Final:
    needs: "Logica"
    runs-on: ubuntu-latest
    steps:
      - name: Final
        run: |
            echo "este es el Final"